name: build-and-sign-windows

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  win:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: use node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: install deps
        run: yarn --ignore-engines --ignore-platform --frozen-lockfile

      - name: build and sign Windows artifact
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: "--openssl-legacy-provider"
          CI: ""
        run: |
          yarn build
          yarn dist-win

      - name: upload signed artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-signed
          path: "**/*.exe"
